common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  <<: *common
  database: allincomefoods
  host: postgres
  port: 5432
  username: postgres
  password:

test:
  <<: *common
  database: allincomefoods_test
  host: postgres
  port: 5432
  username: postgres
  password:
